[package]
name = "rocket-loadavg-api"
version = "0.1.0"
authors = ["Sebastián Magrí <sebasmagri@gmail.com>"]

[dependencies]
libc = "*"
rocket = "0.1.5"
rocket_codegen = "0.1.5"
rocket_contrib = { version = "0.1.5", features = ["json"] }
serde = "*"
serde_json = "*"
serde_derive = "*"